#!/bin/bash
#
# user-info.sh gathers the user's uids and key preferences

set -a
set -e

# keep this for testing
. whiptail_helper.sh
. init.sh

# UIDS
whiptail_input "PRIMARY_UID" "PRIMARY_UID_TEXT" "PRIMARY_UID_TITLE" 
whiptail_input "ADD_UIDS" "ADD_UIDS_TEXT" "ADD_UIDS_TITLE" 

# MASTER KEY
whiptail_input "MASTER_KEY_ALGO" "MASTER_KEY_ALGO_TEXT" "MASTER_KEY_ALGO_TITLE" "MASTER_KEY_ALGO_DEFAULT"
whiptail_input "MASTER_EXPIRY" "EXPIRY_TEXT" "MASTER_EXPIRY_TITLE" "MASTER_EXPIRY_DEFAULT" 

# SECONDARY KEY
whiptail_input "SUBKEY_ALGO" "SUBKEY_ALGO_TEXT" "SUBKEY_ALGO_TITLE" "SUBKEY_ALGO_DEFAULT"
whiptail_input "SUBKEY_EXPIRY" "EXPIRY_TEXT" "SUBKEY_EXPIRY_TITLE" "SUBKEY_EXPIRY_DEFAULT" 

# PASSWORD: Validate that password is 12 chars and confirm password
while true
do
	while true
	do
		whiptail_password "PASSWORD" "PASSWORD_TEXT" "PASSWORD_TITLE"
		[ ${#PASSWORD} -ge 12 ] && break
	done
	whiptail_password "CONF_PASSWORD" "CONF_PASSWORD_TEXT" "CONF_PASSWORD_TITLE"
	[ $PASSWORD = $CONF_PASSWORD ] && break
done

# ENCRYPTION SUBKEY
if whiptail_yesno "ENCR_SUBKEY_YESNO_TEXT" "ENCR_SUBKEY_YESNO_TITLE"; then
	whiptail_input "ENCR_SUBKEY" "ENCR_SUBKEY_TEXT" "ENCR_SUBKEY_TITLE" "SUBKEY_ALGO_DEFAULT"
	whiptail_input "ENCR_SUBKEY_EXPIRY" "EXPIRY_TEXT" "ENCR_SUBKEY_EXPIRY_TITLE" "SUBKEY_EXPIRY_DEFAULT"
fi

# SIGNING SUBKEY
if whiptail_yesno "SIGN_SUBKEY_YESNO_TEXT" "SIGN_SUBKEY_YESNO_TITLE"; then
	whiptail_input "SIGN_SUBKEY" "SIGN_SUBKEY_TEXT" "SIGN_SUBKEY_TITLE" "SUBKEY_ALGO_DEFAULT"
	whiptail_input "SIGN_SUBKEY_EXPIRY" "EXPIRY_TEXT" "SIGN_SUBKEY_EXPIRY_TITLE" "SUBKEY_EXPIRY_DEFAULT"
fi

# AUTHENTICATION SUBKEY
if whiptail_yesno "AUTH_SUBKEY_YESNO_TEXT" "AUTH_SUBKEY_YESNO_TITLE"; then
	whiptail_input "AUTH_SUBKEY" "AUTH_SUBKEY_TEXT" "AUTH_SUBKEY_TITLE" "SUBKEY_ALGO_DEFAULT"
	whiptail_input "AUTH_SUBKEY_EXPIRY" "EXPIRY_TEXT" "AUTH_SUBKEY_EXPIRY_TITLE" "SUBKEY_EXPIRY_DEFAULT"
fi